elvisQuestions = [("When was Elvis born?", False,0), 
                    ('What was Elvis referred to?', False, 0), 
                    ('Where was Elvis born?', False, 0), 
                    ('When did Elvis join the army?', False, 0), 
                    ('At what age did Elvis die?', False, 0), 
                    ('How many Grammys did Elvis win?', False, 0),
                    ('What was Elvis\'s ancestry on this mother\'s side?', False, 4),
                    ('What did Elvis\'s elementary school teachers think of him?', False, 4), 
                    ('Which show did Elvis like to watch on the radio station WELO?', False, 4), 
                    ('How did Elvis learn the guitar?', False, 4), 
                    ('When did Elvis and his family move to Memphis?', False, 5), 
                    ('Who was Elvis\'s first guitar teacher?', False, 5), 
                    ('When did Elvis first visit Sun Records?', False, 8), 
                    ('Which company did Elvis work for as a truck driver?', False, 8), 
                    ('How much money did RCA pay for Elvis\'s contract with Sun Records?', False, 10), 
                    ('When did Elvis make his first recordings for RCA?', False, 13), 
                    ('What did Ed Sullivan call Elvis?', False, 15), 
                    ('Who was Elvis\'s manager after his father?', False, 57),
                    ('Did Elvis\'s music sell well?', False, 64), 
                    ('What was Rock and Roll called before?', False, 52), 
                    ('Did Elvis ever sing gospel music?', False, 47), 
                    ('What influenced Elvis\'s music?', False, 43), 
                    ('When did Presley make his final appearance on Ed Sullivan show?', False, 21),
                    ('What did Elvis\'s mother die of?', False, 24),
                    ('How did Elvis\'s military career end?', False, 26), 
                    ('How many movies did Elvis star in in the 60s?', False, 28), 
                    ('Who is Elvis\'s daughter?', False,31), 
                    ('Did Elvis do drugs?', False, 33), 
                    ('What did Elvis talk about with President Nixon?', False, 35), 
                    ('Who is Tony Brown?', False, 38), 
                    ('Who is Ginger Alden?', False, 39), 
                    ('Who was Elvis buried next to?', False, 40), 
                    ('Which doctor did Elvis\'s autopsy?', False, 41), 
                    ('What are Elvis sandwiches?', False, 42), 
                    ('What was Presley\'s first RCA single', False, 13)]

unanswerable =      [('When did Elvis visit Kiite?', True, -1), 
                    ('When was Bill Gates born?', True, -1), 
                    ('Which video games did Elvis play?', True, -1), 
                    ('What is the best way to fry an egg?', True, -1), 
                    ('What did Elvis think about Mnemonic reader?', True, -1), 
                    ('How many children did they have?', True, -1), 
                    ('Where can I find pictures of Elvis?', True, -1), 
                    ('Who should I go to for Elvis related questions?', True, -1), 
                    ('Where can I buy Elvis t-shirts?', True, -1), 
                    ('How do I contact Elvis?', True, -1), 
                    ('What is the best way to become a rock star?', True, -1)] 

elvisAnswers = ['January 8, 1935', 'King of Rock and Roll', 'Tupelo, Mississipi', '1958', '42', 'three',
                'Scots-Irish', 'average', 'Mississippi Slim', 'Slim supplemented Presley\'s guitar tuition by demonstrating chord techniques',
                'November 1948', 'Lee Denson', 'August 1953', 'Crown Electric', '$40,000', 'January 10, 1956', '"Elvis the Pelvis"', 
                'best-selling solo artist', 'Colonel Tom Parker', 'rhythm and blues', 'Presley would record gospel periodically for the rest of his life', 
                'gospel', 'January 6, 1957', 'hepatitis', 'honorably discharged three days later with the rank of sergeant', '27', 'Lisa Marie', 
                'Presley was not only deeply opposed to recreational drugs, he also rarely drank',
                'expressed his patriotism and explained how he believed he could reach out to the hippies to help combat the drug culture', 
                'Keyboardist', 'new girlfriend', 'his mother', 'Dr. Jerry Francisco', 'fried peanut butter, banana, and (sometimes) bacon sandwiches', 'Heartbreak Hotel']